config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :photos do
      resources :notes
    end
  end

  root 'home#index'

  get 'category/:id' => 'home#category', as: :show_category
  get 'portfolio' => 'home#portfolio'
  get 'photo/:id' => 'home#photo'

  post 'links' => 'hierarchy#add', as: :add_category
  post 'links/:id' => 'hierarchy#delete'

  comfy_route :cms_admin, :path => '/admin'

  comfy_route :cms, :path => '/pages', :sitemap => false

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :category
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", large: "1920x1080#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :notes

  # -- Relationships --------------------------------------------------------


  # -- Callbacks ------------------------------------------------------------


  # -- Validations ----------------------------------------------------------


  # -- Scopes ---------------------------------------------------------------


  # -- Class Methods --------------------------------------------------------


  # -- Instance Methods -----------------------------------------------------
  attr_accessor :noteField

end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Comfy::Admin::Cms::BaseController

  before_action :build_photo,  :only => [:new, :create]
  before_action :load_photo,   :only => [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.page(params[:page])
  end

  def show
    render
  end

  def new
    render
  end

  def edit
    @category = Category.new
    render
  end



  def create
    @photo.save!
    flash[:success] = 'Photo created'
    redirect_to :action => :show, :id => @photo
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to create Photo'
    render :action => :new
  end

  def update
    @photo.update_attributes!(photo_params)
    flash[:success] = 'Photo updated'
    redirect_to :action => :show, :id => @photo
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to update Photo'
    render :action => :edit
  end

  def destroy
    @photo.destroy
    flash[:success] = 'Photo deleted'
    redirect_to :action => :index
  end

protected

  def build_photo
    @photo = Photo.new(photo_params)
  end

  def load_photo
    @photo = Photo.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Photo not found'
    redirect_to :action => :index
  end

  def photo_params
    params.fetch(:photo, {}).permit(:title, :description, :image, :category_id, :homepage)
  end
end

app/views/admin/photos/_form.html.haml
= form.text_field :title
= form.text_field :description
= form.file_field :image
= form.collection_select :category_id, Category.all, :id, :name, prompt: true, include_blank: true
= form.check_box :homepage, :label => 'Show on Homepage'

= form.form_group :class => 'form-actions' do
  = form.submit :class => 'btn btn-primary'

app/views/admin/photos/edit.html.haml
.page-header
  %h2 Edit Photo

= comfy_form_for [:admin, @photo], :html => { :multipart => true } do |form|
  = render form

app/views/admin/photos/index.html.haml
.page-header
  = link_to 'New Photo', new_admin_photo_path, :class => 'btn btn-default pull-right'
  %h2= 'Photos'

= paginate @photos, :theme => 'comfy'

%table.table.table-hover.table-bordered
  %tr
    %th.main Title
    %th Notes
    %th Description
    %th Category
    %th Image
    %th Show on Homepage
    %th
  - @photos.each do |photo|
    %tr
      %td.main= photo.title
      %td= active_link_to 'Notes', admin_photo_notes_path(photo.id)
      %td= photo.description.truncate(50)
      - if photo.category != nil
        %td= photo.category.name
      - else
        %td
      %td= image_tag photo.image.url(:thumb)
      %td
        -if photo.homepage
          = 'Yes'
        -else
          = 'No'
      %td
        .btn-group.btn-group-sm
          = link_to 'Edit', edit_admin_photo_path(photo), :class => 'btn btn-default'
          = link_to 'Delete', admin_photo_path(photo), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'

= paginate @photos, :theme => 'comfy'

admin_photo_notes

app/views/admin/photos/new.html.haml
.page-header
  %h2 New Photo

= comfy_form_for [:admin, @photo], :html => { :multipart => true } do |form|
  = render form

app/views/admin/photos/show.html.haml
.page-header
  %h2 Photo
  
= link_to 'Edit', edit_admin_photo_path(@photo), :class => 'btn btn-default'

%table
  %tr
    %td
      %label Title
    %td 
      = @photo.title

  %tr
    %td
      %label Image
    %td
      = image_tag @photo.image.url(:thumb)