config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :photos do
      resources :notes
    end
  end

  root 'home#index'

  get 'category/:id' => 'home#category', as: :show_category
  get 'portfolio' => 'home#portfolio'
  get 'photo/:id' => 'home#photo'

  post 'links' => 'hierarchy#add', as: :add_category
  post 'links/:id' => 'hierarchy#delete'

  comfy_route :cms_admin, :path => '/admin'

  comfy_route :cms, :path => '/pages', :sitemap => false

end

app/models/contact.rb
class Contact
	include ActiveModel::Model

  attr_accessor :email, :subject, :message

  validates :email, :subject, :message, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    print @contact
    # respond_to do |format|
    #   if @contact.save
    #     format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
    #     format.json { render :show, status: :created, location: @contact }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @contact.errors, status: :unprocessable_entity }
    #   end
    # end

    CommentMailer.comment_email(@contact.email, @contact.subject, @contact.message).deliver
    redirect_to '/pages/contact'
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :subject, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :subject
    = f.text_field :subject
  .field
    = f.label :message
    = f.text_field :message
  .actions
    = f.submit 'Send'

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1 Listing contacts

%table
  %thead
    %tr
      %th Email
      %th Subject
      %th Message
      %th
      %th
      %th

  %tbody
    - @contacts.each do |contact|
      %tr
        %td= contact.email
        %td= contact.subject
        %td= contact.message
        %td= link_to 'Show', contact
        %td= link_to 'Edit', edit_contact_path(contact)
        %td= link_to 'Destroy', contact, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
%section{:class => "container contact-container"}
	%div{:class => "row fullWidth"}
		%div{:class => "small-12 large-12 columns noPadding control-container"}

			%h1 Send us a message

			= render 'form'

app/views/contacts/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @contact.email
%p
  %b Subject:
  = @contact.subject
%p
  %b Message:
  = @contact.message

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path