config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :photos do
      resources :notes
    end
  end

  root 'home#index'

  get 'category/:id' => 'home#category', as: :show_category
  get 'portfolio' => 'home#portfolio'
  get 'photo/:id' => 'home#photo'

  post 'links' => 'hierarchy#add', as: :add_category
  post 'links/:id' => 'hierarchy#delete'

  comfy_route :cms_admin, :path => '/admin'

  comfy_route :cms, :path => '/pages', :sitemap => false

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :children, class_name: "Category", foreign_key: "parent_id"
  has_many :photos
 
  belongs_to :parent, class_name: "Category"

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  # -- Relationships --------------------------------------------------------


  # -- Callbacks ------------------------------------------------------------


  # -- Validations ----------------------------------------------------------


  # -- Scopes ---------------------------------------------------------------


  # -- Class Methods --------------------------------------------------------


  # -- Instance Methods -----------------------------------------------------


end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Comfy::Admin::Cms::BaseController
  before_action :build_category,  :only => [:new, :create]
  before_action :load_category,   :only => [:show, :edit, :update, :destroy]

  def index
    @categories = Category.page(params[:page])
  end

  def show
    render
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @category.save!
    flash[:success] = 'Category created'
    redirect_to :action => :show, :id => @category
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to create Category'
    render :action => :new
  end

  def update
    if params[:parent].blank?
      params[:parent] = nil
    end
    @category.update_attributes!(category_params)
    flash[:success] = 'Category updated'
    redirect_to :action => :show, :id => @category
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to update Category'
    render :action => :edit
  end

  def destroy
    @category.destroy
    flash[:success] = 'Category deleted'
    redirect_to :action => :index
  end

protected

  def build_category
    @category = Category.new(category_params)
  end

  def load_category
    @category = Category.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Category not found'
    redirect_to :action => :index
  end

  def category_params
    params.fetch(:category, {}).permit(:name, :description, :parent_id, :image, :key)
  end
end

app/views/admin/categories/_form.html.haml
= form.text_field :name
/ = form.text_field :key
= form.text_field :description
/ = form.collection_select :parent_id, Category.all, :id, :name, prompt: true, include_blank: true
= form.file_field :image

= form.form_group :class => 'form-actions' do
  = form.submit :class => 'btn btn-primary'

app/views/admin/categories/edit.html.haml
.page-header
  %h2 Edit Category

= comfy_form_for [:admin, @category], :html => { :multipart => true } do |form|
  = render form

app/views/admin/categories/index.html.haml
.page-header
  = link_to 'New Category', new_admin_category_path, :class => 'btn btn-default pull-right'
  %h2= 'Categories'

= paginate @categories, :theme => 'comfy'

%table.table.table-hover.table-bordered
  %tr
    %th.main Name
    / %th Key
    %th Description
    / %th Parent
    %th Image
    %th
  - @categories.each do |category|
    %tr
      %td.main= category.name
      / %td= category.key
      %td= category.description
      / - if category.parent
      /   %td= category.parent.name
      / - else
      /   %td
      %td= image_tag category.image.url(:thumb)
      %td
        .btn-group.btn-group-sm
          = link_to 'Edit', edit_admin_category_path(category), :class => 'btn btn-default'
          = link_to 'Delete', admin_category_path(category), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'

= paginate @categories, :theme => 'comfy'

app/views/admin/categories/new.html.haml
.page-header
  %h2 New Category

= comfy_form_for [:admin, @category], :html => { :multipart => true } do |form|
  = render form

app/views/admin/categories/show.html.haml
.page-header
  %h2 Category
  
= debug @category