config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :photos do
      resources :notes
    end
  end

  root 'home#index'

  get 'category/:id' => 'home#category', as: :show_category
  get 'portfolio' => 'home#portfolio'
  get 'photo/:id' => 'home#photo'

  post 'links' => 'hierarchy#add', as: :add_category
  post 'links/:id' => 'hierarchy#delete'

  comfy_route :cms_admin, :path => '/admin'

  comfy_route :cms, :path => '/pages', :sitemap => false

end

app/models/note.rb
class Note < ActiveRecord::Base

  # -- Relationships --------------------------------------------------------
  belongs_to :photo

  # -- Callbacks ------------------------------------------------------------


  # -- Validations ----------------------------------------------------------


  # -- Scopes ---------------------------------------------------------------


  # -- Class Methods --------------------------------------------------------


  # -- Instance Methods -----------------------------------------------------


end

app/controllers/admin/notes_controller.rb
class Admin::NotesController < Comfy::Admin::Cms::BaseController

  before_action :build_note,  :only => [:new, :create]
  before_action :load_note,   :only => [:show, :edit, :update, :destroy]
  before_action :load_photo

  def index
    @notes = @photo.notes
  end

  def show
    render
  end

  def new
    @note.x = '0'
    @note.y = '0'
    render
  end

  def edit
    render
  end

  def create
    @note.photo_id = @photo.id
    @note.save!
    flash[:success] = 'Note created'
    redirect_to :action => :show, :id => @note
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to create Note'
    render :action => :new
  end

  def update
    @note.update_attributes!(note_params)
    flash[:success] = 'Note updated'
    redirect_to :action => :show, :id => @note
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to update Note'
    render :action => :edit
  end

  def destroy
    @note.destroy
    flash[:success] = 'Note deleted'
    redirect_to :action => :index
  end

protected

  def load_photo
    @photo = Photo.find(params[:photo_id])
  end


  def build_note
    @note = Note.new(note_params)
  end

  def load_note
    @note = Note.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Note not found'
    redirect_to :action => :index
  end

  def note_params
    params.fetch(:note, {}).permit(:name, :description, :photo, :x, :y)
  end
end

app/views/admin/notes/_form.html.erb
<div class="notes-image">
	<div class="note-dot"></div>
	<%= image_tag  @photo.image.url() %>
</div>

<%= form.text_field :name %>
<%= form.text_field :description %>

<%= form.hidden_field :x %>
<%= form.hidden_field :y %>

<%= form.form_group :class => 'form-actions' do %>
	<%= form.submit :class => 'btn btn-primary' %>
<% end %>

<script>
	var image = $('.notes-image img');
	var container = $('.notes-image');
	var dot = $('.note-dot');
	var y = <%= @note.y %>;
	var left = <%= @note.x %>;
	setDot();

	image.click(function(event){
		y = event.offsetY / image.height();
		left = event.offsetX / image.width();
		setDot();
	});

	function setDot(){
		$('#note_x').val(left);
		$('#note_y').val(y);
		dot.css({top: y * image.height(), left: left * image.width()});
	}
</script>

app/views/admin/notes/edit.html.haml
.page-header
  %h2 Edit Note

= comfy_form_for [:admin, @photo, @note] do |form|
  = render form

app/views/admin/notes/index.html.haml
.page-header
  = link_to 'New Note', new_admin_photo_note_path, :class => 'btn btn-default pull-right'
  %h2= 'Notes'
  %h3= @photo.title

%table.table.table-hover.table-bordered
  %tr
    %th.main Name
    %th Description
    %th
  - @notes.each do |note|
    %tr
      %td.main= note.name
      %td= note.description
      %td
        .btn-group.btn-group-sm
          = link_to 'Edit', edit_admin_photo_note_path(@photo, note), :class => 'btn btn-default'
          = link_to 'Delete', admin_photo_note_path(@photo, note), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'

app/views/admin/notes/new.html.haml
.page-header
  %h2 New Note

= comfy_form_for [:admin, @photo, @note] do |form|
  = render form

app/views/admin/notes/show.html.haml
.page-header
  %h2 Note
  
= link_to 'Edit', edit_admin_photo_note_path(@photo, @note), :class => 'btn btn-default'
= link_to 'Go back to Notes List', admin_photo_notes_path(@photo), :class => 'btn btn-default'

%table
  %tr
    %td
      %label Title
    %td 
      = @note.name

  %tr
    %td
      %label Description
    %td
      = @note.description